# Model Training

Train candidate machine learning models for air quality prediction.

In [1]:
import numpy as np
import pandas as pd

from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.impute import SimpleImputer

from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# Prepare features and train models here.

In [2]:
df = pd.read_csv(
    "../data/processed/engineered_air_quality.csv"
)

df["Date"] = pd.to_datetime(df["Date"])

df.shape

(16963, 39)

In [3]:
train_df = df[df["Date"] < "2019-01-01"].copy()

val_df = df[
    (df["Date"] >= "2019-01-01") &
    (df["Date"] < "2020-01-01")
].copy()

test_df = df[df["Date"] >= "2020-01-01"].copy()

In [4]:
print(train_df.shape)
print(val_df.shape)
print(test_df.shape)

(10524, 39)
(4269, 39)
(2170, 39)

In [5]:
num_features = [
    "Valid_AQI",
    "PM2.5",
    "PM10",
    "NO2",
    "CO",
    "SO2",
    "O3",

    "AQI_Lag1",
    "AQI_Lag2",
    "AQI_Lag3",
    "AQI_Lag7",
    "AQI_Roll3",
    "AQI_Roll7",

    "PM2.5_Lag1",
    "PM10_Lag1",
    "NO2_Lag1",
    "CO_Lag1",
    "SO2_Lag1",
    "O3_Lag1",

    "AQI_Change1",
    "PM25_Change1",

    "Month_Sin",
    "Month_Cos",
    "DayOfYear_Sin",
    "DayOfYear_Cos"
]

cat_features = [
    "City",
    "Season",
    "DayOfWeek"
]

features = num_features + cat_features

In [6]:
X_train = train_df[features]
y_train = train_df["Target_AQI"]

X_val = val_df[features]
y_val = val_df["Target_AQI"]

X_test = test_df[features]
y_test = test_df["Target_AQI"]

In [7]:
print(X_train.shape, y_train.shape)
print(X_val.shape, y_val.shape)
print(X_test.shape, y_test.shape)

(10524, 28) (10524,)
(4269, 28) (4269,)
(2170, 28) (2170,)

In [8]:
baseline = val_df[
    ["Valid_AQI", "Target_AQI"]
].dropna()

baseline_pred = baseline["Valid_AQI"]

mae = mean_absolute_error(
    baseline["Target_AQI"],
    baseline_pred
)

rmse = np.sqrt(
    mean_squared_error(
        baseline["Target_AQI"],
        baseline_pred
    )
)

r2 = r2_score(
    baseline["Target_AQI"],
    baseline_pred
)

print("Baseline MAE:", round(mae, 2))
print("Baseline RMSE:", round(rmse, 2))
print("Baseline R2:", round(r2, 3))

Baseline MAE: 22.25
Baseline RMSE: 35.54
Baseline R2: 0.823

In [9]:
numeric_transformer = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler())
])

In [10]:
categorical_transformer = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    (
        "encoder",
        OneHotEncoder(
            handle_unknown="ignore"
        )
    )
])

In [11]:
preprocessor = ColumnTransformer([
    (
        "num",
        numeric_transformer,
        num_features
    ),
    (
        "cat",
        categorical_transformer,
        cat_features
    )
])

In [12]:
linear_model = Pipeline([
    ("preprocessor", preprocessor),
    ("model", LinearRegression())
])

In [13]:
linear_model.fit(
    X_train,
    y_train
)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['Valid_AQI', 'PM2.5', 'PM10',
                                                   'NO2', 'CO', 'SO2', 'O3',
                                                   'AQI_Lag1', 'AQI_Lag2',
                                                   'AQI_Lag3', 'AQI_Lag7',
                                                   'AQI_Roll3', 'AQI_Roll7',
                                                   'PM2.5_Lag1', 'PM10_Lag1',
                                                   'NO2_Lag1', 'CO_Lag1',
                                                   'SO2_Lag1', 'O3_Lag1',
                                                   'AQI_Change1',
                                                   'PM25_Change1', 'Month_Sin',
                                                   'Month_Cos', 'DayOfYear_Sin',
                                                   'DayOfYear_Cos']),
                                                 ('cat',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoder',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['City', 'Season',
                                                   'DayOfWeek'])])),
                ('model', LinearRegression())])

In [14]:
linear_pred = linear_model.predict(X_val)

In [15]:
linear_mae = mean_absolute_error(
    y_val,
    linear_pred
)

linear_rmse = np.sqrt(
    mean_squared_error(
        y_val,
        linear_pred
    )
)

linear_r2 = r2_score(
    y_val,
    linear_pred
)

print("Linear Regression")
print("MAE:", round(linear_mae, 2))
print("RMSE:", round(linear_rmse, 2))
print("R2:", round(linear_r2, 3))

Linear Regression
MAE: 19.49
RMSE: 29.0
R2: 0.885

In [16]:
rf_model = Pipeline([
    ("preprocessor", preprocessor),
    ("model", RandomForestRegressor(
        n_estimators=300,
        max_depth=15,
        min_samples_split=5,
        min_samples_leaf=2,
        random_state=42,
        n_jobs=-1
    ))
])

In [17]:
rf_model.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['Valid_AQI', 'PM2.5', 'PM10',
                                                   'NO2', 'CO', 'SO2', 'O3',
                                                   'AQI_Lag1', 'AQI_Lag2',
                                                   'AQI_Lag3', 'AQI_Lag7',
                                                   'AQI_Roll3', 'AQI_Roll7',
                                                   'PM2.5_Lag1', 'PM10_Lag1',
                                                   'NO2_Lag1', 'CO_Lag1',
                                                   'SO2_Lag1', 'O3_Lag1',
                                                   'AQ...
                                                   'PM25_Change1', 'Month_Sin',
                                                   'Month_Cos', 'DayOfYear_Sin',
                                                   'DayOfYear_Cos']),
                                                 ('cat',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoder',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['City', 'Season',
                                                   'DayOfWeek'])])),
                ('model',
                 RandomForestRegressor(max_depth=15, min_samples_leaf=2,
                                       min_samples_split=5, n_estimators=300,
                                       n_jobs=-1, random_state=42))])

In [18]:
rf_pred = rf_model.predict(X_val)

In [19]:
rf_mae = mean_absolute_error(y_val, rf_pred)

rf_rmse = np.sqrt(
    mean_squared_error(y_val, rf_pred)
)

rf_r2 = r2_score(y_val, rf_pred)

print("Random Forest")
print("MAE:", round(rf_mae, 2))
print("RMSE:", round(rf_rmse, 2))
print("R2:", round(rf_r2, 3))

Random Forest
MAE: 17.38
RMSE: 26.57
R2: 0.903

In [20]:
gb_model = Pipeline([
    ("preprocessor", preprocessor),
    ("model", GradientBoostingRegressor(
        n_estimators=200,
        learning_rate=0.05,
        max_depth=3,
        min_samples_split=5,
        min_samples_leaf=2,
        random_state=42
    ))
])

In [21]:
gb_model.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['Valid_AQI', 'PM2.5', 'PM10',
                                                   'NO2', 'CO', 'SO2', 'O3',
                                                   'AQI_Lag1', 'AQI_Lag2',
                                                   'AQI_Lag3', 'AQI_Lag7',
                                                   'AQI_Roll3', 'AQI_Roll7',
                                                   'PM2.5_Lag1', 'PM10_Lag1',
                                                   'NO2_Lag1', 'CO_Lag1',
                                                   'SO2_Lag1', 'O3_Lag1',
                                                   'AQ...
                                                   'PM25_Change1', 'Month_Sin',
                                                   'Month_Cos', 'DayOfYear_Sin',
                                                   'DayOfYear_Cos']),
                                                 ('cat',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoder',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['City', 'Season',
                                                   'DayOfWeek'])])),
                ('model',
                 GradientBoostingRegressor(learning_rate=0.05,
                                           min_samples_leaf=2,
                                           min_samples_split=5,
                                           n_estimators=200,
                                           random_state=42))])

In [22]:
gb_pred = gb_model.predict(X_val)

In [23]:
gb_mae = mean_absolute_error(y_val, gb_pred)

gb_rmse = np.sqrt(
    mean_squared_error(y_val, gb_pred)
)

gb_r2 = r2_score(y_val, gb_pred)

print("Gradient Boosting")
print("MAE:", round(gb_mae, 2))
print("RMSE:", round(gb_rmse, 2))
print("R2:", round(gb_r2, 3))

Gradient Boosting
MAE: 17.83
RMSE: 27.13
R2: 0.899

In [24]:
results = pd.DataFrame({
    "Model": [
        "Baseline",
        "Linear Regression",
        "Random Forest",
        "Gradient Boosting"
    ],

    "MAE": [
        mae,
        linear_mae,
        rf_mae,
        gb_mae
    ],

    "RMSE": [
        rmse,
        linear_rmse,
        rf_rmse,
        gb_rmse
    ],

    "R2": [
        r2,
        linear_r2,
        rf_r2,
        gb_r2
    ]
})

results.sort_values("MAE")

               Model        MAE       RMSE        R2
2      Random Forest  17.376287  26.572671  0.903237
3  Gradient Boosting  17.832694  27.134901  0.899099
1  Linear Regression  19.487974  29.002286  0.884733
0           Baseline  22.246750  35.541667  0.823028

In [25]:
from xgboost import XGBRegressor

In [26]:
xgb_model = Pipeline([
    ("preprocessor", preprocessor),
    ("model", XGBRegressor(
        n_estimators=500,
        learning_rate=0.03,
        max_depth=6,
        subsample=0.8,
        colsample_bytree=0.8,
        objective="reg:squarederror",
        random_state=42,
        n_jobs=-1
    ))
])

In [27]:
xgb_model.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['Valid_AQI', 'PM2.5', 'PM10',
                                                   'NO2', 'CO', 'SO2', 'O3',
                                                   'AQI_Lag1', 'AQI_Lag2',
                                                   'AQI_Lag3', 'AQI_Lag7',
                                                   'AQI_Roll3', 'AQI_Roll7',
                                                   'PM2.5_Lag1', 'PM10_Lag1',
                                                   'NO2_Lag1', 'CO_Lag1',
                                                   'SO2_Lag1', 'O3_Lag1',
                                                   'AQ...
                              feature_types=None, feature_weights=None,
                              gamma=None, grow_policy=None,
                              importance_type=None,
                              interaction_constraints=None, learning_rate=0.03,
                              max_bin=None, max_cat_threshold=None,
                              max_cat_to_onehot=None, max_delta_step=None,
                              max_depth=6, max_leaves=None,
                              min_child_weight=None, missing=nan,
                              monotone_constraints=None, multi_strategy=None,
                              n_estimators=500, n_jobs=-1,
                              num_parallel_tree=None, ...))])

In [28]:
xgb_pred = xgb_model.predict(X_val)

In [29]:
xgb_mae = mean_absolute_error(y_val, xgb_pred)

xgb_rmse = np.sqrt(
    mean_squared_error(y_val, xgb_pred)
)

xgb_r2 = r2_score(y_val, xgb_pred)

print("XGBoost")
print("MAE:", round(xgb_mae, 2))
print("RMSE:", round(xgb_rmse, 2))
print("R2:", round(xgb_r2, 3))

XGBoost
MAE: 17.22
RMSE: 26.1
R2: 0.907

In [30]:
results = pd.DataFrame({
    "Model": [
        "Baseline",
        "Linear Regression",
        "Random Forest",
        "Gradient Boosting",
        "XGBoost"
    ],

    "MAE": [
        mae,
        linear_mae,
        rf_mae,
        gb_mae,
        xgb_mae
    ],

    "RMSE": [
        rmse,
        linear_rmse,
        rf_rmse,
        gb_rmse,
        xgb_rmse
    ],

    "R2": [
        r2,
        linear_r2,
        rf_r2,
        gb_r2,
        xgb_r2
    ]
})

results.sort_values("MAE")

               Model        MAE       RMSE        R2
4            XGBoost  17.224760  26.102898  0.906628
2      Random Forest  17.376287  26.572671  0.903237
3  Gradient Boosting  17.832694  27.134901  0.899099
1  Linear Regression  19.487974  29.002286  0.884733
0           Baseline  22.246750  35.541667  0.823028